urls.py
from django.urls import path

from . import views

app_name = "Research_work"

urlpatterns = [
    path("",views.index,name="index_page"),
    path("signup/",views.signup,name="signup_page"),
    path("research-home/",views.research,name="research_home_page"),
    path("publication",views.publication,name="publication_page"),
    path("add_publication",views.add_publication,name="add_publication_page"),
    path("reseach_grant",views.research_grant,name="research_grant_page"),
    path("add_research_grant",views.add_research_grant,name="add_research_grant_page"),
    path("consultancy",views.consultancy,name="consultancy_page"),
    path("add_consultancy",views.add_consultancy,name="add_consultancy_page"),
    path("admin_page",views.admin_page,name="admin_access_page"),
    path("logout/",views.logout_view,name="logout_page")
    
]

templates/add_consultancy_work.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=	, initial-scale=1.0">
    <title>Add Consultancy Work</title>
    <link  rel="stylesheet" href="../static/all_add_research_work.css">
</head>
<body>
    
<body style="background-color:#eff3f6;">

    <h1>Enter the details of Consultancy Work</h1>

    <hr>
    <form action="{% url 'Research_work:add_consultancy_page' %}" method="post">
        {% csrf_token %} 
        {{ add_consultancy_work_form.as_p }}

        <input type="submit" value="Add">
    </form>
</html>

templates/add_publications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=	, initial-scale=1.0">
    <title>Add Publications</title>
    <link  rel="stylesheet" href="../static/all_add_research_work.css">
</head>
<body>
    
<body style="background-color:#eff3f6;">

    <h1>Enter the details of Publication</h1>

    <hr>
    <form action="{% url 'Research_work:add_publication_page' %}" method="post">
        {% csrf_token %} 
        
        {{ add_publication_form.as_p }}

        
        {% if field.help_text %}
        <br>
        <small style="color:rgb(102, 102, 102);">{{ field.help_text }}</small>
        {% endif %}

        <input type="submit" value="Add">
    </form>
</html>

templates/add_research_grant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=	, initial-scale=1.0">
    <title>Add Research Grant</title>
    <link  rel="stylesheet" href="../static/all_add_research_work.css">
</head>
<body>
    
<body style="background-color:#eff3f6;">

    <h1>Enter the details of Resarch Grant</h1>

    <hr>
    <form action="{% url 'Research_work:add_research_grant_page' %}" method="post">
        {% csrf_token %} 
        {{ add_research_grant_form.as_p }}

        <input type="submit" value="Add">
    </form>
</html>

templates/admin_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
</head>
<body>
    <h1>ADMIN PAGE</h1>
    <hr>

    


    <form action="" method="post" style="margin-left: 15%;">
        {% csrf_token %}
        <label for="select-teacher"><h3 style="display: inline;">Select a Teacher</h3></label>
        <select name="select-teacher" id="select-teacher" onchange='this.form.submit()'>
            <option value="">...</option>
            <option value="ALL">ALL</option>
            {% for teacher in teacher_name %}
                <option>{{ teacher }}</option>
            {% endfor %}
        </select>
    </form>
    
<div>

    <h2>PUBLICATIONS</h2>
    {% for teacher in teachers %}
        
        <p></p>
        <p>{{ teacher.username }} </p>
        <p>{{ teacher.publications.all }}</p>

        <hr>
        
    {% endfor %}

    
</div>

<div>
    <h2>Research Grant</h2>

    {% for teacher in teachers %}
        
        <p></p>
        <p>{{ teacher.username }} </p>
        <p>{{ teacher.research_grants.all }}</p>

        <hr>
        
    {% endfor %}
</div>

<div>
    <h2>Consultancy</h2>

    {% for teacher in teachers %}
        
        <p></p>
        <p>{{ teacher.username }} </p>
        <p>{{ teacher.consultancies.all }}</p>

        <hr>
        
    {% endfor %}
</div>

<div>
    <h2>Patent</h2>

    {% for teacher in teachers %}
        
        <p></p>
        <p>{{ teacher.username }} </p>
        <p>{{ teacher..all }}</p>

        <hr>
        
    {% endfor %}
</div>
        

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    {% block css_files %}
    {% endblock css_files %}


    <meta charset="utf-8">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="../static/base.css">
  </head>
  <body style="background-color:#eff3f6;">
    <div class="header">
      <table>
        <tr>
          <td>  <img id='img-align' src="../static/images/logo.png" alt=""></td>
          <td class="txt-align"><h1>WELCOME</h1>
          <p><b>SJBIT RESEARCH PORTAL</b></p></td>
        </tr>
      </table>

      

</div>

<div class="navbar">
  <a href="{% url 'Research_work:research_home_page'%}" class="active">Home</a>
  <a href="{% url 'Research_work:publication_page'%}">Publication</a>
  <a href="{% url 'Research_work:research_grant_page'%}">Research Grant</a>
  <a href="{% url 'Research_work:consultancy_page'%}">Consultancy</a>
  <a href="#">Patent</a>
</div>

{% if request.user.is_authenticated %}  
        <h4 style="float:right;clear:both;margin-top: 10px;margin-right: 10px;">Hello, {{ request.user.username }} || <a href="{% url 'Research_work:logout_page' %}">LOGOUT</a> </h4> 
{% endif %}

<br><br><br>

{% block body %}
{% endblock %}


  </body>
</html>

templates/consultancy.html
{% extends 'base.html' %}

{% load static %}

    {% block css_files %}
        <link  rel="stylesheet" href="../static/all_research_work.css">
    {% endblock css_files %}

    {% block title %}
        Consultancy
    {% endblock title %}

    {% block body %}
    <p class="allignleft">Existing Consultancy Work</p>
    
    <a href="{% url 'Research_work:add_consultancy_page'%}" class="myButton clearfix">Add Consultancy work</a>

    <br>

    <form action="" method="post" style="margin-left: 15%;">
        {% csrf_token %}
        <label for="select-year"><h3 style="display: inline;">Select a Year</h3></label>
        <select name="select-year" id="select-year" onchange='this.form.submit()'>
            <option value="">...</option>
            <option value="ALL">ALL</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
        </select>
        
    </form>     

    <div class="">
      <table id="customers">
        <tr>
            <th>Name</th>
            <th>Consultancy Name</th>
            <th>Consultancy Project Name</th>
            <th>Sponsoring agency</th>
            <th>Revenue Granted Date</th>
            <th>Revenue Generated work</th>
            <th>Status of work</th>

            
        </tr>

        {% for consultancy in consultancies %}

        <tr>
            <td>{{ consultancy.teacher_email_id.username }}</td>
            <td>{{ consultancy.name_of_consultancy}}</td>
            <td>{{ consultancy.name_of_consultancy_project}}</td>
            <td>{{ consultancy.sponsoring_agency}}</td>
            <td>{{ consultancy.revenue_granted_date}}</td>
            <td>    {{ consultancy.revenue_generated}}</td>
            <td>{{ consultancy.status_of_consultancy_work}}</td>
                    
        </tr>

        {% endfor %}
     </table>    
    </div>
    {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <link href="../static/index.css" rel="stylesheet">
  </head>

  <body class="text-center">

   

    <form class="form-signin" action="{% url 'Research_work:index_page' %}" method="post">

      {% if message %}
      <h2 style="color:red"> {{ message }}</h2>
      {% endif %}


      <img class="mb-4" src="../static/images/logo.png" alt="" width="100" height="100">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

      {% csrf_token %} 

      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Login in</button><br>
      New User?  <h4 style="display:inline;"> <a href="{% url 'Research_work:signup_page' %}">   Sign up </h4></a>

    
    </form>


  </body>
</html>

templates/publications.html
{% extends 'base.html' %}

{% load static %}

    {% block css_files %}
        <link  rel="stylesheet" href="../static/all_research_work.css">
    {% endblock css_files %}

    {% block title %}
        Publications
    {% endblock title %}

    {% block body %}
    <p class="allignleft">Existing Publications</p>
    
    <a href="{% url 'Research_work:add_publication_page'%}" class="myButton clearfix">Add Publication</a>

    <br>

    <form action="" method="post" style="margin-left: 15%;">
        {% csrf_token %}
        <label for="select-year"><h3 style="display: inline;">Select a Year</h3></label>
        <select name="select-year" id="select-year" onchange='this.form.submit()'>
            <option value="">...</option>
            <option value="ALL">ALL</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
        </select>
        
    </form>

    <div class="">
      <table id="customers">
        <tr>
            <th>Name</th>
            <th>Title</th>
            <th>Author</th>
            <th>issn or issbn</th>
            <th>Journal Name</th>
            <th>Publication Type</th>
            <th>Date of Publication</th>
            <th>DOI</th>
            <th>Impact Factor</th>
            <th>Publication Status</th>
        </tr>

        {% for publication in publications %}

        <tr>
            <td>{{ publication.teacher_email_id.username }}</td>
            <td>{{ publication.paper_title }}</td>
            <td>{{ publication.paper_authors}}</td>
            <td>{{ publication.issn_or_issbn}}</td>
            <td>{{ publication.journal_name_or_conference_name }}</td>
            <td>{{ publication.publication_type }}</td>
            <td>{{ publication.date_of_publication }}</td>
            <td>{{ publication.DOI }}</td>
            <td>{{ publication.impact_factor}}</td>
            <td> {{ publication.publication_status }}</td>
                    
        </tr>

        {% endfor %}
     </table>    
    </div>
    {% endblock %}

templates/research_grant.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}
        <link  rel="stylesheet" href="../static/all_research_work.css">
{% endblock css_files %}

{% block title %}
        Research Grant
{% endblock title %}

{% block body %}
    <p class="allignleft">Existing Research Grants</p>
    
    <a href="{% url 'Research_work:add_research_grant_page'%}" class="myButton clearfix">Add Research Grants</a>

    <br>
    
    <form action="" method="post" style="margin-left: 15%;">

        {% csrf_token %}
        <label for="select-year"><h3 style="display: inline;">Select a Year</h3></label>
        <select name="select-year" id="select-year" onchange='this.form.submit()'>
            <option value="">...</option>
            <option value="ALL">ALL</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
        </select>
        
    </form>


    <div class="">
        <table id="customers">
          <tr>
              <th>Name</th>
              <th>Project Title</th>
              <th>Principle Investigator</th>
              <th>Co-Principle Investigator</th>
              <th>Funding Agency</th>
              <th>Scheme</th>
              <th>Project Status</th>
              <th>Granted Date</th>
              <th>Submitted Date</th>
              
          </tr>
  
          {% for research_grant in research_grants %}
  
          <tr>
              <td>{{ research_grant.teacher_email_id.username }}</td>
              <td>{{ research_grant.project_title }}</td>
              <td>{{ research_grant.principle_investigator_name }}</td>
              <td>{{ research_grant.co_principle_investigator_name }}</td>
              <td>{{ research_grant.funding_agency }}</td>
              <td>{{ research_grant.scheme }}</td>
              <td>{{ research_grant.project_status }}</td>
              <td>{{ research_grant.granted_date }}</td>
              <td>{{ research_grant.submitted_date }}</td>
              
                      
          </tr>
  
          {% endfor %}
       </table>    
      </div>
{% endblock body %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="../static/signup.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

</head>
<body style="background-color:#eff3f6;">
     
    <div class="">
        <h1>Create account</h1>
    </div>

    <form action="{% url 'Research_work:signup_page' %}" method="post">
        {% csrf_token %} 

        {% for field in registration_form %}
            <p>
                {{ field.label_tag }}
                {{ field }}


                {% if field.help_text %}
                    <small style="color:grey;">   {{ field.help_text }}</small>

                {% endif %}


                {% for error in field.errors %}
                     <div style="color:red"> {{ error }} </div> 
                {% endfor %}
            </p>

        {% endfor %}
        <input  type="submit" value="Signup">
    </form>



</body>
</html>

templates/teachers_info.html
{% extends 'base.html' %}

    {% block css_files %}

        <link rel="stylesheet" href="../static/teachers_info.css">

    {% endblock css_files %}

    {% block title %}
        More Info
    {% endblock title %}

    {% block body %}

    <br>
    <div class="">
        <h1>Basic Information</h1>
    </div>

    <hr>

    <form action="{% url 'Research_work:teachers_info_page' %}" method="post">
        {% csrf_token %} 
        {{ new_form.as_p }}
        <input  type="submit" value="Sign Up">
    </form>

    {% endblock body %}